flags: {}
packages:
- '.'
- location:
    git: https://github.com/dbp/fn
    commit: 40d69da801fa67f4c7f6d82dc9e1a9f73f39c48f
  extra-dep: true
  subdirs:
    - fn
extra-deps:
- hspec-2.2.0
- hspec-core-2.2.0
- hspec-expectations-0.7.2
- hspec-discover-2.2.0
resolver: lts-2.17
